---
title: "ch2_regression"
author: "hiramekun"
date: "4/23/2021"
output:
  html_document: default
  pdf_document: default
---
## Rによるメールマーケティングデータの分析（回帰編）

```{r}
# (1) パッケージをインストールする（初回のみ）
install.packages("broom", dependencies = TRUE, repos = "http://cran.jp.r-project.org")

# (2) ライブラリの読み出し
library("tidyverse")
library("broom")

# (3) データの読み込み
email_data <- read_csv("http://www.minethatdata.com/Kevin_Hillstrom_MineThatData_E-MailAnalytics_DataMiningChallenge_2008.03.20.csv")

# (4) 女性向けメールが配信されたデータを削除したデータを作成
male_df <- email_data %>%
  filter(segment != "Womens E-Mail") %>% # 女性向けメールが配信されたデータを削除
  mutate(treatment = ifelse(segment == "Mens E-Mail", 1, 0)) # 介入を表すtreatment変数を追加

# (5) セレクションバイアスのあるデータを作成
## seedを固定
set.seed(1)

## 条件に反応するサンプルの量を半分にする
obs_rate_c <- 0.5
obs_rate_t <- 0.5

## バイアスのあるデータを作成
biased_data <- male_df %>%
  mutate(obs_rate_c =
           ifelse( (history > 300) | (recency < 6) |
                     (channel == "Multichannel"), obs_rate_c, 1),
         obs_rate_t =
           ifelse( (history > 300) | (recency < 6) |
                     (channel == "Multichannel"), 1, obs_rate_t),
         random_number = runif(n = NROW(male_df))) %>%
  filter( (treatment == 0 & random_number < obs_rate_c ) |
            (treatment == 1 & random_number < obs_rate_t) )

```
```{r}
biased_reg <- lm(data = biased_data,
                 formula = spend ~ treatment + history)
summary(biased_reg)
```

```{r}
biased_reg_coef <- tidy(biased_reg)
biased_reg_coef
```

```{r}
rct_reg <- lm(data = male_df, formula = spend ~ treatment)
rct_reg_coef <- summary(rct_reg) %>% tidy()

nonrct_reg <- lm(data = biased_data, formula = spend ~ treatment)
nonrct_reg_coef <- summary(nonrct_reg) %>% tidy()
```

```{r}
rct_reg_coef
```
```{r}
nonrct_reg_coef
```

```{r}
nonrct_mreg <- lm(data = biased_data, 
                  formula = spend ~ treatment + recency + channel + history)
nonrct_mreg_coef <- tidy(nonrct_mreg)
nonrct_mreg_coef
```
```{r}
formula_vec <- c(spend ~ treatment + recency + channel,
                 spend ~ treatment + recency + channel + history,
                 history ~ treatment + channel + recency)
names(formula_vec) <- paste("reg", LETTERS[1:3], sep="_")
models <- formula_vec %>%
  enframe(name= "model_index", value = "formula")
df_models <- models %>%
  mutate(model = map(.x = formula, .f = lm, data = biased_data)) %>%
  mutate(lm_result = map(.x = model, .f = tidy))

df_results <- df_models %>%
  mutate(formula = as.character(formula)) %>%
  select(formula, model_index, lm_result) %>%
  unnest(cols = c(lm_result))

treatment_coef <- df_results %>%
  filter(term == "treatment") %>%
  pull(estimate)

history_coef <- df_results %>%
  filter(model_index == "reg_B",
         term == "history") %>%
  pull(estimate)

OVB <- history_coef * treatment_coef[3]
coef_gap <- treatment_coef[1] - treatment_coef[2]
```
```{r}
OVB
```
```{r}
coef_gap
```
```{r}
cor_visit_treatment <- lm(
  data = biased_data,
  formula = treatment ~ visit + channel + recency + history
) %>%
  tidy()
cor_visit_treatment
```
```{r}
bad_control_reg <- lm(
  data = biased_data,
  formula = spend ~ treatment + channel + recency + history + visit
) %>%
  tidy()
bad_control_reg
```