---
title: "ch1_bias"
author: "hiramekun"
date: "4/21/2021"
output:
  html_document: default
  pdf_document: default
---

```{r}
install.packages("tidyverse", dependencies = TRUE, repos = "http://cran.jp.r-project.org")
library("tidyverse")
```

## RCTを行ったデータの準備
```{r}
email_data <- read.csv("http://www.minethatdata.com/Kevin_Hillstrom_MineThatData_E-MailAnalytics_DataMiningChallenge_2008.03.20.csv")
male_df <- email_data %>%
  filter(segment != "Womens E-Mail") %>%
  mutate(treatment = if_else(segment == "Mens E-Mail", 1, 0))
```

## RCTデータの集計と有意差検定
```{r pressure, echo=FALSE}
summary_by_segment <- male_df %>%
  group_by(treatment) %>%
  summarize(conversion_rate = mean(conversion),
            spend_mean = mean(spend),
            count = n())

mens_mail <- male_df %>%
  filter(treatment == 1) %>%
  pull(spend)

no_mail <- male_df %>%
  filter(treatment == 0) %>%
  pull(spend)

rct_ttest <- t.test(mens_mail, no_mail, var.equal = TRUE)
```
```{r}
rct_ttest
```
t.test()は平均の差が本当は0である確率を評価しており、その確率はp-valueで評価される

## バイアスのあるデータによる効果の検証

 - メールが配信されていないグループでは、条件に当てはまるデータを50%の確率で削除。
 - メールが配信されているグループでは、条件に当てはまらないデータを50%の確率で削除。
 
```{r}
set.seed(1)
obs_rate_c <- 0.5
obs_rate_t <- 0.5

biased_data <- male_df %>%
  mutate(
    obs_rate_c = if_else(
      history > 300 | recency < 6 | channel == "Multichannel", obs_rate_c, 1
      ),
    obs_rate_t = if_else(
      history > 300 | recency < 6 | channel == "Multichannel", 1, obs_rate_t
      ),
    random_number = runif(n = NROW(male_df))
    ) %>%
  filter((treatment == 0 & random_number < obs_rate_c) | 
           (treatment == 1 & random_number < obs_rate_t))
```

バイアスデータで集計と有意差検定
```{r}
summary_by_segment_biased <- biased_data %>%
  group_by(treatment) %>%
  summarize(conversion_rate = mean(conversion),
            spend_mean = mean(spend),
            count = n())

mens_mail_biased <- biased_data %>%
  filter(treatment == 1) %>%
  pull(spend)

no_mail_biased <- biased_data %>%
  filter(treatment == 0) %>%
  pull(spend)

rct_ttest_biased <- t.test(mens_mail_biased, no_mail_biased, var.equal = TRUE)
```
```{r}
rct_ttest_biased
```

p-valueがバイアスなしの時よりも小さくなっていることがわかる。つまり、平均の差はより広がっている。